version: "v1.21.0+k3s1"
image: "centos/7"
token: "agent-token"
ip_range: "10.0.0."
interface: "eth1"
masters:
  count: 1
  resources:
    memory: "512"
    cpu: "1"
workers:
  count: 2
  resources:
    memory: "256"
    cpu: "1"
